/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkModeSwitcher: typeof import('./src/components/dark-mode-switcher/index.vue')['default']
    DatePicker: typeof import('./src/components/date-picker/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    JsonForm: typeof import('./src/components/json-form/index.vue')['default']
    JsonFormItem: typeof import('./src/components/json-form-item/index.vue')['default']
    JsonTable: typeof import('./src/components/json-table/index.vue')['default']
    LogoLink: typeof import('./src/components/logo-link/index.vue')['default']
    MainColorSwitcher: typeof import('./src/components/main-color-switcher/index.vue')['default']
    MobileMenu: typeof import('./src/components/mobile-menu/index.vue')['default']
    Pagination: typeof import('./src/components/pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenuTooltip: typeof import('./src/components/side-menu-tooltip/index.vue')['default']
    SingleUpload: typeof import('./src/components/upload/single-upload.vue')['default']
    TopBar: typeof import('./src/components/top-bar/index.vue')['default']
    Upload: typeof import('./src/components/Upload/Upload.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
